from __future__ import annotations
from typing import List, Dict, Optional, Union, Any
from pydantic import BaseModel, Field, ConfigDict

# =============================================================================
# GITHUB ACTIONS DOMAIN MODEL
# Main Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
# =============================================================================

# ---------------------------------------------------------
# 1. Step Definition
# ---------------------------------------------------------
class Step(BaseModel):
    """
    Represents an individual task within a Job.
    
    A step is an individual task that can run commands in a job. A step can be either
    a shell command or an action definition.
    
    Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps
    """
    model_config = ConfigDict(populate_by_name=True)

    # The name that is displayed in the GitHub Actions UI for this step.
    name: Optional[str] = None
    
    # A unique identifier for the step. Allows referencing it in contexts 
    # (e.g., steps.<id>.outputs).
    id: Optional[str] = None
    
    # Conditional expression. The step will only run if this condition evaluates to true.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
    if_condition: Optional[str] = Field(default=None, alias="if") 
    
    # Selects an action to run as part of a step in your job. 
    # Mutually exclusive with 'run'.
    # Example: actions/checkout@v4
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
    uses: Optional[str] = None
    
    # Runs command-line programs using the operating system's shell.
    # Mutually exclusive with 'uses'.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
    run: Optional[str] = None
    
    # Specifies the working directory where the 'run' command will be executed.
    # If not defined, it uses the job's default.
    working_directory: Optional[str] = Field(default=None, alias="working-directory")
    
    # Allows overriding the default shell configuration in the runner's operating system.
    # Example: 'bash', 'pwsh', 'python'.
    shell: Optional[str] = None
    
    # A map of the input parameters required by the action defined in 'uses'.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith
    with_args: Optional[Dict[str, Any]] = Field(default=None, alias="with") 
    
    # Sets environment variables available only for this step.
    env: Optional[Dict[str, Union[str, int, bool]]] = None
    
    # Prevents the job from failing if this step fails. 
    # If true, the job continues to the next step even if this one returns an error.
    continue_on_error: Optional[bool] = Field(default=False, alias="continue-on-error")
    
    # The maximum number of minutes to run the step before killing the process.
    timeout_minutes: Optional[int] = Field(default=None, alias="timeout-minutes")


# ---------------------------------------------------------
# 2. Job Definition
# ---------------------------------------------------------
class Job(BaseModel):
    """
    Represents a set of steps that execute on the same runner.
    Jobs run in parallel by default, unless 'needs' is used.
    
    Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobs
    """
    model_config = ConfigDict(populate_by_name=True)

    # The name of the job displayed on GitHub.
    name: Optional[str] = None
    
    # Identifies any jobs that must complete successfully before this job will run.
    # Creates sequential dependencies between jobs.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds
    needs: Optional[Union[str, List[str]]] = None 
    
    # Defines the type of machine to run the job on.
    # Example: "ubuntu-latest", "windows-2019", or self-hosted tags.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs_on: Union[str, List[str]] = Field(alias="runs-on")
    
    # Modifies the default permissions granted to the GITHUB_TOKEN for this job.
    permissions: Optional[Union[str, Dict[str, str]]] = None
    
    # Defines the environment that the job references.
    # Used for protection rules and environment-specific secrets (e.g., 'production').
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment
    environment: Optional[Union[str, Dict[str, Any]]] = None
    
    # A map of outputs generated by this job that will be available to 
    # other jobs that depend on this one.
    outputs: Optional[Dict[str, str]] = None
    
    # Environment variables available for all steps in the job.
    env: Optional[Dict[str, Union[str, int, bool]]] = None
    
    # Default configuration that will apply to all steps in the job.
    defaults: Optional[Dict[str, Any]] = None
    
    # Conditional to prevent the job from running unless the condition is met.
    if_condition: Optional[str] = Field(default=None, alias="if")
    
    # The list of steps (tasks) that make up the job.
    steps: List[Step] = []
    
    # A matrix strategy allows creating multiple job runs based on variable combinations.
    # Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy: Optional[Dict[str, Any]] = None 
    
    # Ensures that only a single job or workflow runs at a time in the same concurrency group.
    concurrency: Optional[Union[str, Dict[str, Any]]] = None
    
    # Service containers (like Redis, Postgres) to host services needed for the job.
    services: Optional[Dict[str, Any]] = None


# ---------------------------------------------------------
# 3. Trigger Definition (On)
# ---------------------------------------------------------
# The 'on' attribute defines which events trigger the workflow.
# Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#on
WorkflowTrigger = Union[str, List[str], Dict[str, Any]]


# ---------------------------------------------------------
# 4. Workflow Definition (Root)
# ---------------------------------------------------------
class Workflow(BaseModel):
    """
    Root model representing the entire .yaml configuration file.
    A workflow is a configurable automated process composed of one or more jobs.
    
    Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#about-workflows
    """
    model_config = ConfigDict(populate_by_name=True)

    # The name of the workflow. GitHub displays this name in the "Actions" tab.
    name: Optional[str] = None
    
    # The name for workflow runs generated from the workflow.
    # Allows dynamic names using contexts.
    run_name: Optional[str] = Field(default=None, alias="run-name")
    
    # Event or events that trigger the workflow. REQUIRED.
    on: WorkflowTrigger
    
    # Modifies the default GITHUB_TOKEN permissions for the entire workflow.
    permissions: Optional[Union[str, Dict[str, str]]] = None
    
    # Environment variables available to all jobs and steps in the workflow.
    env: Optional[Dict[str, Union[str, int, bool]]] = None
    
    # A set of jobs that the workflow executes. REQUIRED.
    # Defined as a dictionary because in YAML keys are job IDs.
    jobs: Dict[str, Job]

    # Global concurrency management for the workflow.
    concurrency: Optional[Union[str, Dict[str, Any]]] = None


# ---------------------------------------------------------
# 5. Repository Definition (New Entity)
# ---------------------------------------------------------
class Repository(BaseModel):
    """
    Represents a code repository (e.g., a project folder or a remote Git repo)
    that contains a collection of Workflows.
    
    This entity serves as a container to facilitate cross-workflow analysis 
    and consistency checks across the entire project.
    """
    # The name or identifier of the repository (e.g., 'owner/repo-name').
    name: str
    
    # Dictionary containing all parsed workflows found in the .github/workflows directory.
    # Key: The filename (e.g., 'ci.yml').
    # Value: The parsed Workflow object.
    workflows: Dict[str, Workflow] = Field(default_factory=dict)

    def total_workflows(self) -> int:
        """Returns the total number of valid workflows loaded for this repository."""
        return len(self.workflows)

    def get_workflow_names(self) -> List[str]:
        """Returns a list of the names of all workflows in the repository."""
        return [w.name for w in self.workflows.values() if w.name]